### ISSUE TITLE
focal ppa: add python as dependency

### ISSUE THREAD

**Issue by enigma9o7** [smplayer-dev/smtube#2]
For the longest time I thought that the smtube version I had didn't work.  Long story short, python 2 has to be installed for youtuble-dl to function, but when smtube just grabs the binary, no dependencies get installed, and I only had python3.   It wasn't pulled in as a dependency when I installed smtube from ppa.   So suggest adding python to control file for smtube.

**Comment by smplayer-dev** [comment]
I think it's fixed now. 
https://github.com/smplayer-dev/smtube/commit/ff60305f707030669621e18f35a4285d6be4df1f
