### ISSUE TITLE
Debian 11 Repository?

### ISSUE THREAD

**Issue by enigma9o7** [smplayer-dev/smtube#3]
The debian 10 package on your website works, but it would be nice to be able to add a repository meant for bullseye.  

Currently it only offers up to debian 10.  Debian 11 bullseye is still testing but stable release should be this summer sometime and I'm sure I'm not the only using it already...

**Comment by ghost** [comment]
Debian 12 is released.

**Comment by enigma9o7** [comment]
> Debian 12 is released.

A while ago.  And official debian stable repo includes a fairly recent version , plus the smplayer 3rd party repo includes support for not only debian 11 as I originally opened this for, but also debian 12.    If they want to add something, it'd be for debian 13, but no real need, current version is already in debian's official testing repo, and 13/trixie  wont release for more than a year and a half from now.

I'm closing this issue, shoulda been closed long time ago!
