### ISSUE TITLE
Youtube Mainpage Refuses to load gets to <90% and crashes.

### ISSUE THREAD

**Issue by MrRKernelPanic** [smplayer-dev/smtube#4]
**Describe the bug**
Unitl recently I've very happily used SMTube to browse to videos on youtube, on an SBC like an RPI4 it loads much quicker than a browser and it is easy to open videos with VLC.

**To Reproduce**
1. Go to 'http://www.youtube.com/' or 'http://mobile.youtube.com'
2. trying to login to youtube now leads to 'bad request' or carrying out a search returns 'Invalid Response Received'

**Expected behavior**
Page should load with subscription videos.

**Your Enviroment**
 - SMTube version:Version: 20.6.0 (revision 1033)
Compiled with Qt 5.11.3 (using 5.11.3)

 - OS: Raspberry Pi OS (32bit) Buster.

This error my entirely be due to a change in Youtube.

**Comment by smplayer-dev** [comment]
smtube is designed to display the website tonvid.com. If it works with other sites is just by chance. I'm afraid I can't fix this problem because it actually seems a problem in the qtwebkit library.

**Comment by MrRKernelPanic** [comment]
Turns out I think this was a bug with Youtube authentification. I cleared cookies and also the cache files to located in ~/.config/smtube and the browsers settings. This seemed to do the trick. Excellent software I really love and would recommend.
